### ISSUE TITLE
Collision is disabled for some city labels

### ISSUE THREAD

**Issue by matteblair** [tangrams/traditional-style#25]
https://github.com/tangrams/cinnabar-style/blob/gh-pages/cinnabar-style.yaml#L4205

This has been observed to produce some overlapping labels in tangram-es:
![screenshot_20170503-180040](https://cloud.githubusercontent.com/assets/3371850/25683576/cea8cdf4-302a-11e7-9d61-6bb0658cf437.png)

**Comment by nvkelso** [comment]
Good find!

Looks like it’s just that one line (the others are for UX elements that
should behave as the code describes).

**Comment by nvkelso** [comment]
Fixed via 61987e8b66a5b2fe2426f7da7a63cba56b3b124c.
