### ISSUE TITLE
show major barriers like barrier=fence or barrier=wall

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/traditional-style#26]
Is there a chance that PR implementing feature like this would be accepted?

**Comment by nvkelso** [comment]
Go for it! I think it's just moving existing styling around.

**Comment by nvkelso** [comment]
Fixed in https://github.com/tangrams/cinnabar-style/commit/7d905d4b382097e297bc87908629632a29a0f6e8.

**Comment by nvkelso** [comment]
@matkoniecz This is released in https://github.com/tangrams/cinnabar-style/releases/tag/v7.0.1 and on the Mapzen CDN.

**Comment by matkoniecz** [comment]
@nvkelso Thanks!
