### ISSUE TITLE
Not rendering road over building correctly

### ISSUE THREAD

**Issue by winfried** [tangrams/traditional-style#30]
See: westnordost/StreetComplete#292

**Comment by matkoniecz** [comment]
@winfried It may be a good idea yo copy entire  issue text (as poster you can edit original and copy-paste text).

**Comment by nvkelso** [comment]
That's an interesting bug, will have a look.

**Comment by nvkelso** [comment]
<img width="729" alt="screen shot 2017-06-09 at 12 57 24" src="https://user-images.githubusercontent.com/853051/26992369-3a89f098-4d13-11e7-972b-c8abd9936919.png">

_Most_ but not all terrace "basement" buildings are tagged `layer=-1` here so filtering on that in the style I can tell them **not** to extrude. Fixing that will need a stylesheet change still. I'll leave it up to you if you want to keep this issue open to ingest the new stylesheet or not.

**Comment by nvkelso** [comment]
Fixed in https://github.com/tangrams/cinnabar-style/commit/41f7108a14bd51fe968d2e8d7950763a4a977bfe but needs to be formally released.

**Comment by matkoniecz** [comment]
Thanks for a very quick fix!
