### ISSUE TITLE
use cap: round for paths and roads

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/traditional-style#36]
I am not planning making PR due to very high complexity of style, but it seems that cap:round would be useful for paths

for example https://github.com/matkoniecz/cinnabar-style/commit/33aec7e90652b09c43c228e107579a86e9fb06da makes following difference at https://mapzen.com/tangram/play/?#20.00000/50.08020/19.88489

from
![selection_003](https://user-images.githubusercontent.com/899988/27252598-e938c420-5362-11e7-910b-7ac81aa88326.png)

to
![selection_004](https://user-images.githubusercontent.com/899988/27252602-efb7fdde-5362-11e7-951b-fe6302891738.png)

It affects not only baths - see bottom right of https://user-images.githubusercontent.com/13661397/27248826-e48fa0ae-5300-11e7-9349-2d1e065eb34d.png (spotted in https://github.com/westnordost/StreetComplete/pull/340)

**Comment by nvkelso** [comment]
Looks like the same `cap: round` fix could be applied to most Mapzen basemap styles.

I vaguely recall this not being done last year because it introduces a performance hit – we could address that by limiting to zoom 16 or 17+ only.

**Comment by sensescape** [comment]
fixed:

https://github.com/tangrams/cinnabar-style/commit/480557206f2e82c50b069dab87ad3c261cd21d1a

<img width="774" alt="screen shot 2017-08-03 at 11 05 11 am" src="https://user-images.githubusercontent.com/466585/28936222-e0d4cb6e-783b-11e7-9533-6b5f98ce457b.png">

**Comment by nvkelso** [comment]
Fixed in https://github.com/tangrams/cinnabar-style/issues/42, but needs public release to CDN.
