### ISSUE TITLE
poor display of bridge over pond in the park

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/traditional-style#37]
http://www.openstreetmap.org/?mlat=50.06578&mlon=19.94020#map=19/50.06578/19.94020
https://mapzen.com/tangram/play/?#20.00000/50.06576/19.94025

Note that bridge starting on the edge of water is correct mapping for that case (I guess that problem is caused by displaying pond bigger than mapped, or making edge of water appear on top of footway).

![selection_002](https://user-images.githubusercontent.com/899988/28260674-746c619c-6adc-11e7-93be-2908fcdd1c5f.png)

**Comment by nvkelso** [comment]
Most other Mapzen house styles (like Bubble Wrap) don't suffer from this problem so it's definitely fixable. It's possible the `sort_rank` coming thru tiles is off (the boundary line of the water has a different sort_rank than the fill), I need to investigate more.

**Comment by sensescape** [comment]
fixed:

<img width="821" alt="screen shot 2017-08-03 at 10 54 01 am" src="https://user-images.githubusercontent.com/466585/28935655-1d0d5378-783a-11e7-8822-c560219911ab.png">

https://github.com/tangrams/cinnabar-style/commit/d0b21b4537336e8641ce0a4f92e64bac18265797

**Comment by nvkelso** [comment]
Fixed in https://github.com/tangrams/cinnabar-style/issues/42, but needs public release to CDN.
