### ISSUE TITLE
highway=pedestrian + area=yes (squares, plazas) are missing

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/traditional-style#39]
Pedestrian areas were added in some tangram styles after https://github.com/tilezen/vector-datasource/issues/1312

example: https://mapzen.com/tangram/play/?#20.00000/50.05667/19.93490

**Comment by nvkelso** [comment]
Fixed via https://github.com/tangrams/cinnabar-style/commit/ed8fd92f98030bf5852764db633cb0a0f0b1a082 and released.

**Comment by nvkelso** [comment]
This is now live on the CDN.
