### ISSUE TITLE
How to use cinnabar style with openLayers 3?

### ISSUE THREAD

**Issue by costales** [tangrams/traditional-style#4]
I see documentation for Leaflet. Can I use cinnabar style with openLayers too?
Is there any basic example? Thanks in advance!

Please, take a look to a [basic example](http://jsfiddle.net/fmu2tnq3/4/) (I see only the vectors, without the tangrams scene).

**Comment by nvkelso** [comment]
Hi @costales. We aren't currently setup to work with OpenLayers. There's nothing hard stopping this integration, but it Leaflet has been our focus so far. We'd gladly accept a PR for an integration, though! 

At this point Tangram mostly just gets the view position from Leaflet, and the plugin needs to know how to best position its <canvas> element to fit in with the underlying map.

**Comment by nvkelso** [comment]
We've added OpenLayers example here:

- https://github.com/mapzen/openlayers-mapzen-vector-tile-example/

**Comment by costales** [comment]
Hi Nathaniel,
This is awesome! Thanks a lot for the port!
Just 1 thing please, in the example:
https://cdn.rawgit.com/pafavero/map-vector-tile-simple/master/index.html
the tangram layer disappears with zoom 16+.
Should I open an issue for this?
Thanks in advance!

-- 
-- 
Sent using Dekko from my Ubuntu device

**Comment by am2222** [comment]
@nvkelso Hi, Does this version works with 3d too?If yes it is awesome
