### ISSUE TITLE
broken oneway arrows

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/traditional-style#41]
I attempted to reuse code from https://github.com/tangrams/cinnabar-style/commit/26f200e6c9c7b5204fd5ca38a4380a4621c6112a to add oneway arrows and discovered that arrow sprite appears to be broken

Arrow sprite seems to be a rectangle - effect is visible in
https://mapzen.com/tangram/play/?#18.50000/50.06934/19.94990

![selection_003](https://user-images.githubusercontent.com/899988/28260881-43d9e134-6add-11e7-85d6-6bf85980f2fd.png)

(note small squares scattered across roads)

I tested arrow sprite definition to display at specified POI, small square also appeared there.

In addition I see no oneway sprite in https://github.com/tangrams/cinnabar-style/commit/26f200e6c9c7b5204fd5ca38a4380a4621c6112a#diff-e82ec2de2911d77ed0457513f4f705a7

**Comment by matkoniecz** [comment]
It may be also my mistake - how one is supposed to update graphic files in tangram play? I assumed that graphic files from tangram styles are automatically available (as I see no way to upload graphic file) but maybe I am mistaken.

**Comment by nvkelso** [comment]
I’ll have a look.

On Thu, Jul 20, 2017 at 4:38 AM, Mateusz Konieczny <notifications@github.com

**Comment by nvkelso** [comment]
Somehow the sprite sheet regressed to the older version without the white arrow – but Tangram doesn't know that in the YAML, it just looks for an XY region of a certain width and height in the image and displays that.

Cinnabar reuses the spritesheet from Refill (it doesn't have it's own customized icons). The sprite sheets are managed in Adobe **Illustrator** files with an export script. The repo is here: https://github.com/tangrams/icons

In any event, it's all fixed and working [now](https://github.com/tangrams/cinnabar-style/tree/2782f81b8d6b2ab1fa2e7475d1246e769b4fc426) :)

**Comment by nvkelso** [comment]
<img width="1080" alt="screen shot 2017-07-24 at 15 26 27" src="https://user-images.githubusercontent.com/853051/28547601-8078a1a0-7084-11e7-8cfd-d8e525239a86.png">

**Comment by nvkelso** [comment]
Closed via https://github.com/tangrams/cinnabar-style/releases/tag/v7.1.0. Will be on CDN tomorrow morning. (But the bug was never publicly released, was only on master for a time.)

**Comment by nvkelso** [comment]
This is now live on the CDN.
